region             = "us-east-1"
profile            = "shautu-bhau-50tola"
cidr_block         = "10.0.0.0/16"
tags               = "vpc01"
public_cidr_block  = "10.0.1.0/24"
private_cidr_block = "10.0.2.0/24"
instance_type      = "t2.micro"
key_name           = "terraform-key"
